---
title: "Update blocked pyenv update on Windows"
date: 2026-05-29
description: "Update pyenv version cache on Windows when the pyenv update command fails."
categories: [Windows, Python, pyenv]
draft: false
---

# Problem

As of today May 29th 2026, on Windows 11, the `pyenv update` command fails with a "command is not supported" error:

:::: {.code-output}
```powershell
pyenv update
```

<pre class="output-pane">:: [Info] ::  Mirror: https://www.python.org/ftp/python
C:\Users\xxx\.pyenv\pyenv-win\libexec\pyenv-update.vbs(279, 9) htmlfile: Cette commande n'est pas prise en charge.</pre>
::::

This prevents updating the pyenv version cache, making new Python versions unavailable for conveniently [creating a new Python virtual environment](../../snippets/2026-05-22-python_venv_powershell/index.qmd).

The root cause is that Windows 11 no longer supports the VBScript used in `pyenv-update.vbs` (see issue [#715](https://github.com/pyenv-win/pyenv-win/issues/715)).


# Update pyenv package

Check the current pyenv version:

:::: {.code-output}
```powershell
pyenv --version
```

<pre class="output-pane">pyenv 3.1.1</pre>
::::

Latest Python versions available in the pyenv cache:

:::: {.code-output}
```powershell
pyenv install --list
```

<pre class="output-pane">...
3.14.1
3.14.2
...
3.14.3
3.15.0a7
...</pre>
::::

Attempt to update the pyenv package to get the latest fixes:

:::: {.code-output}
```powershell
pip install --upgrade pyenv-win --target "$HOME\.pyenv"
```

<pre class="output-pane">Collecting pyenv-win
  Using cached pyenv_win-3.1.1-py3-none-any.whl.metadata (24 kB)
Using cached pyenv_win-3.1.1-py3-none-any.whl (3.6 MB)
Installing collected packages: pyenv-win
Successfully installed pyenv-win-3.1.1</pre>
::::

Check the pyenv version:

:::: {.code-output}
```powershell
pyenv --version
```

<pre class="output-pane">pyenv 3.1.1</pre>
::::

Check the pyenv cache:

:::: {.code-output}
```powershell
pyenv install --list
```

<pre class="output-pane">...
3.10.1
3.10.5
...
3.11.0b3
3.11.0b4</pre>
::::

The pyenv Python version cache is now out of date compared to my previous local cache. The pip-installed package ships a very outdated Python version list from 2022 ([latest pyenv-win from pypi](https://pypi.org/project/pyenv-win/#history)) ! 

The fix for the `pyenv update` command is not yet released at the time of writing (see pull request [#724](https://github.com/pyenv-win/pyenv-win/pull/724)) so the pyenv version cache needs to be refreshed with a workaround.


# Update the version cache manually

Instead of applying an unreleased fix or a custom workaround from the issue thread, temporarily update the cache with a simple file replacement to get a fresh list of available Python versions.

::: {.snippet-steps}
1. Get the path of the cache file on the local pyenv installation:

   :::: {.code-output}
   ```powershell
   Get-Command pyenv | Select-Object -ExpandProperty Source
   ```

   <pre class="output-pane">C:\Users\xxx\.pyenv\pyenv-win\bin\pyenv.ps1</pre>
   ::::

   The cache file is located at `C:\Users\xxx\.pyenv\pyenv-win\.versions_cache.xml`

2. Download the [cache file from the pyenv-win repository](https://github.com/pyenv-win/pyenv-win/blob/master/pyenv-win/.versions_cache.xml)

3. Replace the contents of the local cache file with the downloaded version.

4. Check that the list of available Python versions is up to date:

   :::: {.code-output}
   ```powershell
   pyenv install --list
   ```

   <pre class="output-pane">...
   3.14.4
   3.14.5
   ...
   3.15.0b1
   ...</pre>
   ::::
:::


# Testing downloading the latest Python version

:::: {.code-output}
```powershell
pyenv install 3.14.5
```

<pre class="output-pane">:: [Info] ::  Mirror: https://www.python.org/ftp/python
:: [Downloading] ::  3.14.5 ...
:: [Downloading] ::  From https://www.python.org/ftp/python/3.14.5/python-3.14.5-amd64.exe
:: [Downloading] ::  To   C:\Users\xxx\.pyenv\pyenv-win\install_cache\python-3.14.5-amd64.exe
:: [Installing] ::  3.14.5 ...
:: [Info] :: completed! 3.14.5
...</pre>
::::

Check available Python versions on the system:

:::: {.code-output}
```powershell
pyenv versions
```

<pre class="output-pane">...
  3.14.5
...</pre>
::::

# Conclusion

Until an official pyenv fix is released, manually replacing `.versions_cache.xml` with the latest version from the repository is a simple and reliable workaround.
